# Here is the information for creating a config.yaml: https://annotation.github.io/text-fabric/tf/advanced/settings.html
# Here is a good example: https://github.com/annotation/app-bhsa/blob/master/code/config.yaml
apiVersion: 3
dataDisplay:
  noneValues: 
  - none
  - unknown
  - null
  - NA
  - ''
  excludedFeatures:
  - reference
  textFormat: text-orig-full
# sectionSep1: #this is to display sections well in table
# sectionSep2: #this is to display sections well in table
# showVerseInTuple: 
# textFormats:
docs:
  docBase: 'https://tonyjurg.github.io/Nestle1904GBI'
  docPage: 'index'
  featureBase: 'https://tonyjurg.github.io/Nestle1904GBI/features'
  featurePage: 'home'
typeDisplay:
  book:
    label: '{book}'
    style: ""
  verse:
    label: '{book} {chapter} {verse}'
    style: ''
  word:
    label: '#{word}' 
    featuresBare:
      - gloss
    features:
      - lemma
      - strongs
  clause:
    label: '#{clause} {clausetype} {clauserule} '
    style: ""
  phrase:
    label: '#{phrase} {phrasetype} {phrasefunction}'
    style: ""
interfaceDefaults:
  fmt: text-orig-full
  # used by tf browser
provenanceSpec:
  corpus: "Nestle 1904 (GBI nodes)"
  doi: zenodo.notyet
  version: "0.4"
  org: "tonyjurg"
  repro: "Nestle1904GBI"
  webUrl: "https://learner.bible/text/show_text/nestle1904/<1>/<2>/<3>"
  webHint: Show this on the website
  webLang: en
writing: grc
