# Here is the information for creating a config.yaml: https://annotation.github.io/text-fabric/tf/advanced/settings.html
# Here is a good example: https://github.com/annotation/app-bhsa/blob/master/code/config.yaml
# check whether a list with (- - - ) works or whether I need to do a list with commas "a, b, c"
apiVersion: 3
dataDisplay:
  noneValues: 
  - none
  - unknown
  - null
  - NA
  - ''
  excludedFeatures:
  - reference
  textFormat: text-orig-full
# sectionSep1: #this is to display sections well in table
# sectionSep2: #this is to display sections well in table
# showVerseInTuple: 
# textFormats:
# docs: reference to transcription.md
docs:
  docPage: about
  featureBase: '{docBase}/transcription.md'
  featurePage: transcription
typeDisplay:
  book:
    label: '{book}'
    style: ""
  word:
    featuresBare:
      - gloss
    features:
      - lemma
      - strongs
  clause:
    label: '#{clause}'
    style: ""
  phrase:
    label: '#{phrase}'
    style: ""
interfaceDefaults:
  fmt: layout-orig-full
  # used by tf browser
provenanceSpec:
  corpus: "Nestle 1904 (GBI nodes)"
  version: "0.4"
  org: "tonyjurg"
  repro: "Nestle1904GBI"
  webUrl: "https://bibleol.3bmoodle.dk/text/show_text/nestle1904/<1>/<2>/<3>"
writing: grc
